// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgtdckfqodmlyjqolbxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNndGRja2Zxb2RtbHlqcW9sYnh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzY1NzMsImV4cCI6MjA2MjExMjU3M30._mUuzy_5KGXDp7teC_OJrHNp3TwbvN7tVqbLEysZvnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to create storage URLs
export const getStorageUrl = (bucket: string, path: string) => {
  return `${SUPABASE_URL}/storage/v1/object/public/${bucket}/${path}`;
};

// Função para testar a conexão com o Supabase
export const testSupabaseConnection = async () => {
  try {
    // Tenta fazer uma consulta simples para testar a conexão
    const { data, error } = await supabase.from('shipments').select('count').limit(1);
    
    if (error) {
      console.error('Erro na conexão com o Supabase:', error);
      return {
        connected: false,
        error: error.message,
        details: error
      };
    }
    
    return {
      connected: true,
      data
    };
  } catch (error) {
    console.error('Exceção ao testar conexão com o Supabase:', error);
    return {
      connected: false,
      error: error instanceof Error ? error.message : 'Erro desconhecido',
      details: error
    };
  }
};
